name: Hugo

on:
  push:
    branches: [ src ]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.70.0'
          extended: true
      - name: build
        run: hugo
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: master # The branch the action should deploy to.
          FOLDER: ./public # The folder the action should deploy.
